# Python Advance Programming Assignment 17

In [46]:
'''Q1. . Create a function that transposes a 2D matrix.

Examples

transpose_matrix([
  [1, 1, 1],
  [2, 2, 2],
  [3, 3, 3]
]) ➞ [
  [1, 2, 3],
  [1, 2, 3],
  [1, 2, 3]
]

transpose_matrix([
  [5, 5],
  [6, 7],
  [9, 1]
]) ➞ [
  [5, 6, 9],
  [5, 7, 1]
]'''
import numpy as np
def transpose_matrix(arr):
    arr = np.array(arr)
    return print(arr.T,"\n")

transpose_matrix([
  [1, 1, 1],
  [2, 2, 2],
  [3, 3, 3]
]) 

transpose_matrix([
  [5, 5],
  [6, 7],
  [9, 1]
])

[[1 2 3]
 [1 2 3]
 [1 2 3]] 

[[5 6 9]
 [5 7 1]] 



In [47]:
'''Q2. Create a function that determines whether a string is a valid hex code.

A hex code must begin with a pound key # and is exactly 6 characters in length. Each character must be a digit from 0-9 or an alphabetic character from A-F. All alphabetic characters may be uppercase or lowercase.

Examples

is_valid_hex_code("#CD5C5C") ➞ True

is_valid_hex_code("#EAECEE") ➞ True

is_valid_hex_code("#eaecee") ➞ True

is_valid_hex_code("#CD5C58C") ➞ False
# Length exceeds 6

is_valid_hex_code("#CD5C5Z") ➞ False
# Not all alphabetic characters in A-F

is_valid_hex_code("#CD5C&C") ➞ False
# Contains unacceptable character

is_valid_hex_code("CD5C5C") ➞ False
# Missing #'''

def is_valid_hex_code(string):
    valid_char = '#0123456789ABCDEFabcedf'
    for i in string:
        if i not in valid_char or len(string) > 7 or '#' not in string:
            return print(False)
    return print(True)

is_valid_hex_code("#CD5C5C")
is_valid_hex_code("#EAECEE")
is_valid_hex_code("#eaecee")
is_valid_hex_code("#CD5C58C")
is_valid_hex_code("#CD5C5Z")
is_valid_hex_code("#CD5C&C")
is_valid_hex_code("CD5C5C")

True
True
True
False
False
False
False


In [48]:
'''Q3. Given a list of math equations (given as strings), return the percentage of correct answers as a string. Round to the nearest whole number.

Examples

mark_maths(["2+2=4", "3+2=5", "10-3=3", "5+5=10"]) ➞ "75%"

mark_maths(["1-2=-2"]), "0%"

mark_maths(["2+3=5", "4+4=9", "3-1=2"]) ➞ "67%"'''

def mark_maths(lst):
    count = 0
    x = []
    y = []
    
    for i in lst:
        x.append(eval(i[:i.index("=")]))
    
    for j in lst:
        y.append(eval(j[j.index("=")+1:]))
    
    for k in range(len(lst)):
        if x[k] == y[k]:
            count +=1
    print(round(count/len(lst)*100), "%", sep = "")

mark_maths(["2+2=4", "3+2=5", "10-3=3", "5+5=10"])
mark_maths(["1-2=-2"])
mark_maths(["2+3=5", "4+4=9", "3-1=2"])

75%
0%
67%


In [49]:
'''Q4. There are two players, Alice and Bob, each with a 3-by-3 grid. A referee tells Alice to fill out one particular row in the grid (say the second row) by putting either a 1 or a 0 in each box, such that the sum of the numbers in that row is odd. The referee tells Bob to fill out one column in the grid (say the first column) by putting either a 1 or a 0 in each box, such that the sum of the numbers in that column is even.

Alice and Bob win the game if Alice’s numbers give an odd sum, Bob’s give an even sum, and (most important) they’ve each written down the same number in the one square where their row and column intersect.

Examples

magic_square_game([2, "100"], [1, "101"]) ➞ False

magic_square_game([2, "001"], [1, "101"]) ➞ True

magic_square_game([3, "111"], [2, "011"]) ➞ True

magic_square_game([1, "010"], [3, "101"]) ➞ False

# Two lists, Alice [row, "her choice"], Bob [column, "his choice"]'''

import numpy as np
def magic_square_game(alice, bob):
    #alice = [row, her choice]
    #bob = [column, his choice]
    x = [[0,0,0],
          [0,0,0],
          [0,0,0]]
    
    y = [[0,0,0],
          [0,0,0],
          [0,0,0]]
    
    for i in range(len(x)):
        if i == alice[0]-1:
            for j in range(len(x)):
                x[i][j] = int(alice[1][j])
    
    for i in range(len(y)):
        for j in range(len(y)):
            if j == bob[0]-1:
                y[i][j] = int(bob[1][i])
    
    a = alice[0]-1
    b = bob[0]-1
    
    if x[a][b] ==  y[a][b]:
         return print(True)
    else:
        return print(False)
            

magic_square_game([2, "100"], [1, "101"])

magic_square_game([2, "001"], [1, "101"])
    
magic_square_game([3, "111"], [2, "011"])

magic_square_game([1, "010"], [3, "101"])

False
True
True
False


In [50]:
'''Q5. From point A, an object is moving towards point B at constant velocity va (in km/hr). From point B, another object is moving towards point A at constant velocity vb (in km/hr). Knowing this and the distance between point A and B (in km), write a function that returns how much time passes until both objects meet.

Format the output like this:

"2h 23min 34s"

Examples

lets_meet(100, 10, 30) ➞ "2h 30min 0s"

lets_meet(280, 70, 80) ➞ "1h 52min 0s"

lets_meet(90, 75, 65) ➞ "0h 38min 34s"'''

def lets_meet(dist, speed_1, speed_2):
    time = dist/(speed_1+speed_2)
    
    hour = int(time)
    minutes = round((time*60) % 60)
    seconds = round((time*3600) % 60)
    
    print(hour,"h ", minutes,"min ", seconds,"s", sep = "")

lets_meet(100, 10, 30)
lets_meet(280, 70, 80)
lets_meet(90, 75, 65)

2h 30min 0s
1h 52min 0s
0h 39min 34s
